
# cargo-vet config file

[cargo-vet]
version = "0.10"

[policy.dataports]
audit-as-crates-io = true

[[exemptions.dataports]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.doc-comment]]
version = "0.3.4"
criteria = "safe-to-run"
